const FIELD_ROWS = [
  [
    { key: 'partNumber', label: 'Part No.' },
    { key: 'revision', label: 'Rev.' },
  ],
  [{ key: 'drawingTitle', label: 'Drawing Title', span: 2 }],
  [
    { key: 'material', label: 'Material' },
    { key: 'quantity', label: 'Qty' },
  ],
  [
    { key: 'scale', label: 'Scale' },
    { key: 'toleranceClass', label: 'Tolerance' },
  ],
  [
    { key: 'surfaceFinish', label: 'Surface Finish' },
    { key: 'weight', label: 'Weight' },
  ],
  [
    { key: 'drawnBy', label: 'Generated By' },
    { key: 'checkedDate', label: 'Date' },
  ],
]

export default function TitleBlock({ data }) {
  return (
    <div className="overflow-hidden rounded-lg border border-border-strong bg-white shadow-panel">
      <div className="border-b border-border-strong bg-canvas px-4 py-2.5">
        <p className="font-mono text-[11px] uppercase tracking-wider text-muted">
          Title Block · Extracted Summary
        </p>
      </div>
      <div className="divide-y divide-border">
        {FIELD_ROWS.map((row, rowIndex) => (
          <div
            key={rowIndex}
            className="grid"
            style={{ gridTemplateColumns: row.length === 1 ? '1fr' : '1fr 1fr' }}
          >
            {row.map((field, i) => (
              <div
                key={field.key}
                className={`px-4 py-2.5 ${i === 0 && row.length > 1 ? 'border-r border-border' : ''}`}
              >
                <p className="font-mono text-[10px] uppercase tracking-wider text-faint">
                  {field.label}
                </p>
                <p className="mt-0.5 truncate font-mono text-sm text-ink" title={String(data[field.key] ?? '—')}>
                  {data[field.key] ?? '—'}
                </p>
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  )
}
